### ISSUE TITLE
Tweaks to: not(); opt(); WhileCharIn

### ISSUE THREAD

**Issue by evanbennett** [cdietze/parsek#1]
I have been using my own fork with a few small tweaks, and would like to see if you would be interested in accepting the changes here.

1. `not()` could be an operator function:
https://github.com/cdietze/parsek/blob/f61445fc7e37aad755b20cf7e350b8172f977036/src/commonMain/kotlin/parsek/ParserApi.kt#L61

2. I found that I needed an `opt()` function for `Parser<Unit>`:
https://github.com/cdietze/parsek/blob/f61445fc7e37aad755b20cf7e350b8172f977036/src/commonMain/kotlin/parsek/ParserApi.kt#L77

3. You changed `CharIn` and `CharPred` to contain `Char` not `Unit`. Logically this lead me to change `WhileCharIn` to contain `List<Char>` not `Unit`:
https://github.com/cdietze/parsek/blob/f61445fc7e37aad755b20cf7e350b8172f977036/src/commonMain/kotlin/parsek/ParserApi.kt#L39-L40
https://github.com/cdietze/parsek/blob/f61445fc7e37aad755b20cf7e350b8172f977036/src/commonMain/kotlin/parsek/Intrinsics.kt#L32
https://github.com/cdietze/parsek/blob/f61445fc7e37aad755b20cf7e350b8172f977036/src/commonMain/kotlin/parsek/Intrinsics.kt#L39
And the JSON parser test still needs `space` to be `Unit` to pass:
https://github.com/cdietze/parsek/blob/f61445fc7e37aad755b20cf7e350b8172f977036/src/commonTest/kotlin/parsek/JsonParserTest.kt#L39

I am happy to submit a Pull Request if you may be willing to accept these tweaks.

Note: All of these changes (except the test fix) are in a commit (with a few other changes that I wanted, but I am not requesting):
https://github.com/evanbennett/parsek/commit/e879ef2f4b5bf63a9255cb6021ce6545f776809d

**Comment by cdietze** [comment]
Hi!
1. Good suggestion, I just added and pushed that
2. Ah, interesting - the generic version produces a `Parser<Unit?>` but you need a `Parser<Unit>` right? What was your use-case where this issue occurred?
3. The reason is performance: I try to avoid any allocations that may not be necessary. And getting the parsed value back is as easy as calling `capture()` to get a `Parser<String>`

**Comment by evanbennett** [comment]
Hi.

1. Thanks.
2. If I have used `Parser<A>.opt(): Parser<A?>` (so I have `Parser<Unit?>`). Then I need to use the result in a `times`, `Parser<Unit>.times(b: Parser<A>): Parser<A>` and `Parser<A>.times(b: Parser<Unit>): Parser<A>` do not match so `Parser<A>.times(b: Parser<B>): Parser<Pair<A, B>>` is used with A or B being `Unit?`. Which does not seem ideal. (I can give a specific example if this is not clear enough.)
3. I need to spend some time to look into your response.

Thanks.

**Comment by cdietze** [comment]
Concerning 2:
I just pushed an update which makes `times` support to skip over `Parser<Unit?>` instead of `Parser<Unit>`s. Please check it out if that solves your issue.

**Comment by evanbennett** [comment]
Your update concerning 2 absolutely meets my requirements. It also covers any creation of `Parser<Unit?>` (e.g. other than `opt()`), making it more comprehensive. Thank you very much.

I will look into 3 later today.

**Comment by evanbennett** [comment]
I found that most of the time with the `WhileCharIn` is was using `.capture()` in it straight away anyway. The few that I was not, I have updated and it all appears to work fine. Thank you again.

One final question: How do I use the project (now that I do not need customisation)? e.g. Will you publish a new version somewhere that I can use in my dependencies?

**Comment by cdietze** [comment]
You can use the release from jitpack, i just tagged the current version as `v0.2`, see instructions here: https://jitpack.io/#cdietze/parsek

**Comment by evanbennett** [comment]
Hey.

I have added `maven { url = uri("https://jitpack.io") }` to my `repositories` in my build.gradle.kts file.

I have `implementation("com.github.cdietze", "parsek-jvm", "v0.2")` in my `dependencies`. (I also tried "0.2" with the same result.)

I am getting:
```
Execution failed for task ':compileKotlin'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve com.github.cdietze:parsek-jvm:v0.2.
     Required by:
         project :
      > Could not resolve com.github.cdietze:parsek-jvm:v0.2.
         > Could not get resource 'https://jitpack.io/com/github/cdietze/parsek-jvm/v0.2/parsek-jvm-v0.2.pom'.
            > Could not GET 'https://jitpack.io/com/github/cdietze/parsek-jvm/v0.2/parsek-jvm-v0.2.pom'. Received status code 401 from server: Unauthorized
```

Do you know how I might fix this?

**Comment by cdietze** [comment]
I struggled with this myself, you need to use `implementation("com.github.cdietze.parsek", "parsek-jvm", "v0.2")`

**Comment by evanbennett** [comment]
That is working now. Thank you very much.
